# Generated by Django 2.0.3 on 2018-03-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tick',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
